// Generated by CoffeeScript 1.6.3

/*
  * Module dependencies.
 */

(function() {
  var Recipe, app, express, http, mongoURI, mongoose, path, request, routes, yummlyAppId, yummlyAppKey;

  console.log("fire app.js");

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  mongoose = require('mongoose');

  request = require('request');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, '/../public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  yummlyAppId = '48b32423';

  yummlyAppKey = "f801fe2eacf40c98299940e2824de106";

  app.get('/recipes', function(req, res) {
    request("http://api.yummly.com/v1/api/recipes?_app_id=" + yummlyAppId + "&_app_key=" + yummlyAppKey + "&q=onion+chicken", function(error, response, body) {
      var recipeObj, yummlyObj;
      recipeObj = {
        totalMatchCount: 0
      };
      yummlyObj = JSON.parse(body);
      recipeObj.totalMatchCount = yummlyObj['totalMatchCount'];
      recipeObj.matches = yummlyObj['matches'];
      res.send(recipeObj);
      res.send(yummlyObj);
    });
  });

  mongoURI = process.env.MONGOHQ_URL || 'mongodb://localhost/veganizzmapp';

  mongoose.connect(mongoURI);

  Recipe = mongoose.model('Recipe', {
    name: String,
    ingredient: String
  });

  app.get('/', routes.index);

  app.post('/submitdata', function(req, res) {
    var recipe, submitedInfo;
    submitedInfo = req.body;
    console.log("submitedInfo", submitedInfo);
    recipe = new Recipe(submitedInfo);
    recipe.save(function(err, data) {
      console.log("sent to database:", data);
    });
  });

  http.createServer(app).listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
