// Generated by CoffeeScript 1.6.3
(function() {
  var async, request;

  console.log("fire index.js");

  request = require('request');

  async = require('async');

  exports.index = function(req, res) {
    var credentials, getMetaData, searchParam, tasks, toRender;
    searchParam = {
      allergy: 'allergy',
      diet: 'diet',
      cuisine: 'cuisine',
      course: 'course'
    };
    credentials = {
      yummlyAppId: '_app_id=48b32423',
      yummlyAppKey: "&_app_key=f801fe2eacf40c98299940e2824de106"
    };
    getMetaData = function(param, callback) {
      var yummlyUrl;
      yummlyUrl = 'http://api.yummly.com/v1/api/metadata/' + param + '?' + credentials.yummlyAppId + credentials.yummlyAppKey;
      return request(yummlyUrl, function(error, response, body) {
        var data;
        data = body.replace("set_metadata('" + param + "',", '').replace(');', '');
        return callback(null, JSON.parse(data));
      });
    };
    toRender = {
      title: 'Veganizzm App'
    };
    tasks = [
      function(cb) {
        return getMetaData(searchParam.cuisine, function(err, data) {
          toRender.allowedCuisine = data;
          return cb();
        });
      }, function(cb) {
        return getMetaData(searchParam.course, function(err, data) {
          toRender.allowedCourse = data;
          return cb();
        });
      }, function(cb) {
        return getMetaData(searchParam.allergy, function(err, data) {
          toRender.allowedAllergy = data;
          return cb();
        });
      }, function(cb) {
        return getMetaData(searchParam.diet, function(err, data) {
          toRender.allowedDiet = data;
          return cb();
        });
      }
    ];
    return async.series(tasks, function() {
      return res.render('index', toRender);
    });
  };

}).call(this);
