// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  console.log("fire index.js");

  request = require('request');

  exports.index = function(req, res) {
    var credentials, getMetaData, searchParam, whatever;
    searchParam = {
      allergy: 'allergy',
      diet: 'diet',
      cuisine: 'cuisine',
      course: 'course'
    };
    credentials = {
      yummlyAppId: '_app_id=48b32423',
      yummlyAppKey: "&_app_key=f801fe2eacf40c98299940e2824de106"
    };
    getMetaData = function(param, credentials) {
      var pushedData, yummlyUrl;
      yummlyUrl = 'http://api.yummly.com/v1/api/metadata/' + param + '?' + credentials.yummlyAppId + credentials.yummlyAppKey;
      pushedData = [];
      request(yummlyUrl, function(error, response, body) {
        var data;
        data = body.replace("set_metadata('" + param + "',", '').replace(');', '');
        return pushedData.push(JSON.parse(data));
      });
      console.log("jsdafsdf");
      return setTimeout(function() {
        return pushedData[0];
      }, 3000);
    };
    whatever = getMetaData(searchParam.cuisine, credentials);
    console.log("whatever", whatever);
  };

}).call(this);
